---
- name: Include OS specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"

- name: Check if unattended-upgrades is installed
  service_facts:

- name: Stop unattended-upgrades
  service:
    name: unattended-upgrades
    state: stopped
  when: "'unattended-upgrades' in services"

- name: Delete unattended-upgrades
  apt:
    name: unattended-upgrades
    state: absent
  notify: reload systemd

- name: Add rtpengine group
  group:
    name: "{{ rtpengine_group }}"
    state: present
    system: true
  when: rtpengine_group != "root"

- name: Add rtpengine user
  user:
    name: "{{ rtpengine_user }}"
    group: "{{ rtpengine_group }}"
    comment: "rtpengine"
    home: "{{ rtpengine_install_dir }}"
    shell: /bin/false
    system: true
  when: rtpengine_user != "root"
